services:
  identity-and-access-db-migrate:
    profiles: ["tooling"]

    build:
      context: ..
      dockerfile: deploy/liquibase.Dockerfile

    volumes:
      - ../:/workspace:ro

    working_dir: /workspace

    command:
      - --search-path=/workspace
      - --changelog-file=changelog/changelog-master.yaml
      - --url=jdbc:postgresql://postgres:5432/${PG_DATABASE:?PG_DATABASE is required}
      - --username=${PG_ADMIN_USER:?PG_ADMIN_USER is required}
      - --password=${PG_ADMIN_PASSWORD:?PG_ADMIN_PASSWORD is required}
      - --database-changelog-table-name=databasechangelog_identity_and_access
      - --database-changelog-lock-table-name=databasechangeloglock_identity_and_access
      - update

    networks:
      - platform

networks:
  platform:
    external: true
    name: platform
